<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Login Test Suite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>72eaccd8-0291-4aca-9588-38d7df1f1716</testSuiteGuid>
   <testCaseLink>
      <guid>5eeeb772-ab04-40af-8851-5056a5ae2ce0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Borrower Dashboard/Verify Borrower is able to Login</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>737806ac-4c31-47d6-ab77-dad173e463dc</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Login Test Data/Login</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>737806ac-4c31-47d6-ab77-dad173e463dc</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>939b252a-30d3-4b8f-93d7-637f9ae85341</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>737806ac-4c31-47d6-ab77-dad173e463dc</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Password</value>
         <variableId>3f557203-c552-4808-81e5-7a1b8866170d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2a00e6bb-0698-48cd-a58a-4d8d27a7748b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>23f55887-6685-4376-8dae-5eb046788f5a</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
