<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Application_Release_Tab</name>
   <tag></tag>
   <elementGuidId>d1d47158-cb9f-4211-8fa2-315ba2c89255</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='loan_applications_content']/div/div[1]/div/ul/li[9]/a</value>
   </webElementProperties>
</WebElementEntity>
